<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>

        <IsPackable>false</IsPackable>

        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NUnit" Version="3.14.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageReference Include="GitHubActionsTestLogger" Version="3.0.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ninjadini.Neuro.CodeGen\Ninjadini.Neuro.CodeGen.csproj" />
        <PackageReference Include="Microsoft.CodeAnalysis" Version="3.8.0" />
    </ItemGroup>

</Project>
